import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const key = 'english-continuation:v1'
const navigate = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name, exact: true }).click()
const stored = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
async function importFile(page: Page, data: unknown) {
  await page.getByLabel('选择 JSON 备份文件').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
}
async function createMaterial(page: Page) {
  await navigate(page, '素材库管理')
  await page.getByLabel('板块名称', { exact: true }).fill('我的板块')
  await page.getByRole('button', { name: '新增板块', exact: true }).click()
  await page.getByLabel('主题名称', { exact: true }).fill('坚持')
  await page.getByRole('button', { name: '新增主题', exact: true }).click()
  await page.getByLabel('英文', { exact: true }).fill('I kept trying until I succeeded.')
  await page.getByLabel('中文释义', { exact: true }).fill('我不断尝试，直到成功。')
  await page.getByLabel('标签（用逗号分隔）').fill('毅力，比赛, 毅力')
  await page.getByRole('button', { name: '添加模板句', exact: true }).click()
  await page.getByRole('button', { name: '☆ 收藏', exact: true }).click()
}

test('自建素材 → 搜索 → 使用 → 导出 → 覆盖导入恢复', async ({ page }) => {
  await page.goto('/')
  await createMaterial(page)
  await page.getByLabel('板块名称', { exact: true }).fill('我的素材')
  await page.getByRole('button', { name: '保存板块名称' }).click()
  await page.getByLabel('主题名称', { exact: true }).fill('坚持到底')
  await page.getByRole('button', { name: '保存主题名称' }).click()
  await page.getByRole('button', { name: '编辑模板句', exact: true }).click()
  await page.getByLabel('英文', { exact: true }).fill('I kept trying and finally succeeded.')
  await page.getByRole('button', { name: '保存模板句', exact: true }).click()
  await page.screenshot({ path: 'test-results/library.png', fullPage: true })
  await navigate(page, '作文工作台')
  await page.getByLabel('作文标题', { exact: true }).fill('Persistence')
  await page.getByLabel('搜索全部素材').fill('毅力')
  await expect(page.locator('.sentence')).toHaveCount(1)
  await page.getByLabel('只看收藏').check()
  await expect(page.getByRole('button', { name: '★ 已收藏' })).toBeVisible()
  await page.getByRole('button', { name: '＋ 加入作文' }).click()
  const block = page.getByTestId('template-block')
  await block.getByRole('textbox').fill('I kept trying and finally won the race.')
  await expect(block).toContainText('我的素材 · 坚持到底')
  await navigate(page, '设置')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出 JSON' }).click()
  const download = await downloadPromise
  const backup = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(backup.sentences.find((s: { tags?: string[] }) => s.tags?.includes('毅力')).tags).toEqual(['毅力', '比赛'])
  expect(backup.essays[0].paragraph1[0].content).toContain('won the race')
  const beforeReset = backup.essays
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '恢复默认素材库', exact: true }).click()
  expect((await stored(page)).sentences).toHaveLength(32)
  expect((await stored(page)).essays).toEqual(beforeReset)
  await importFile(page, backup)
  await expect(page.getByText('校验通过：', { exact: false })).toBeVisible()
  expect((await stored(page)).sentences).toHaveLength(32)
  await page.getByRole('button', { name: '确认覆盖导入' }).click()
  await expect(page.getByText('导入成功，全部本地数据已恢复。', { exact: false })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('作文标题', { exact: true })).toHaveValue('Persistence')
  await expect(block.getByRole('textbox')).toHaveValue('I kept trying and finally won the race.')
  await expect(block).toContainText('我的素材 · 坚持到底')
  await page.getByLabel('搜索全部素材').fill('SUCCEEDED')
  await expect(page.locator('.sentence')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '★ 已收藏' })).toBeVisible()
  await page.screenshot({ path: 'test-results/phase-two-workbench.png', fullPage: true })
})

test('删除句子、主题和板块后，作文内容与原来源仍然保留', async ({ page }) => {
  await page.goto('/')
  await createMaterial(page)
  await navigate(page, '作文工作台')
  await page.getByLabel('搜索全部素材').fill('毅力')
  await page.getByRole('button', { name: '＋ 加入作文' }).click()
  await navigate(page, '素材库管理')
  await page.getByLabel('搜索全部素材').fill('毅力')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '删除模板句', exact: true }).click()
  await expect(page.locator('.sentence')).toHaveCount(1)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除模板句', exact: true }).click()
  await expect(page.locator('.sentence')).toHaveCount(0)
  const data = await stored(page)
  await page.getByLabel('所属板块', { exact: true }).selectOption(data.categories.find((c: { name: string }) => c.name === '我的板块').id)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除主题', exact: true }).click()
  await expect(page.getByRole('button', { name: '添加模板句', exact: true })).toBeDisabled()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除板块', exact: true }).click()
  await page.reload()
  await expect(page.getByTestId('template-block')).toContainText('我的板块 · 坚持')
  await expect(page.getByTestId('template-block').getByRole('textbox')).toHaveValue('I kept trying until I succeeded.')
})

test('第一阶段草稿迁移、归属级联删除与空库恢复', async ({ page }) => {
  await page.goto('/')
  const legacy = { version: 1, essay: { id: 'legacy', title: '旧作文', sourceText: '题目', paragraph1Starter: 'One day,', paragraph2Starter: 'At last,',
    paragraph1: [{ id: 'old-block', type: 'template', sentenceId: 'nervous-1', content: 'My revised sentence.' }], paragraph2: [] } }
  await page.evaluate(({ key, legacy }) => localStorage.setItem(key, JSON.stringify(legacy)), { key, legacy })
  await page.reload()
  await expect(page.locator('#title')).toHaveValue('旧作文')
  await expect(page.getByTestId('template-block')).toContainText('情绪描写 · 紧张')
  await navigate(page, '素材库管理')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除主题', exact: true }).click()
  let data = await stored(page)
  expect(data.sentences.some((s: { topicId: string }) => s.topicId === 'nervous')).toBe(false)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除板块', exact: true }).click()
  data = await stored(page)
  expect(data.topics.some((t: { categoryId: string }) => t.categoryId === 'emotion')).toBe(false)
  expect(data.sentences.some((s: { categoryId: string }) => s.categoryId === 'emotion')).toBe(false)
  await navigate(page, '设置')
  await importFile(page, { ...data, categories: [], topics: [], sentences: [] })
  await page.getByRole('button', { name: '确认覆盖导入' }).click()
  await navigate(page, '作文工作台')
  await expect(page.getByTestId('template-block').getByRole('textbox')).toHaveValue('My revised sentence.')
  await expect(page.getByLabel('01 / 选择板块')).toBeDisabled()
  await navigate(page, '素材库管理')
  await expect(page.getByRole('button', { name: '新增主题', exact: true })).toBeDisabled()
  await page.getByLabel('板块名称', { exact: true }).fill('重新开始')
  await page.getByRole('button', { name: '新增板块', exact: true }).click()
  await expect(page.getByRole('button', { name: '新增主题', exact: true })).toBeEnabled()
})

test('拒绝错误版本、字段、重复 ID 与非法归属；取消导入保持原数据', async ({ page }) => {
  await page.goto('/')
  const original = await stored(page)
  await navigate(page, '设置')
  const invalid = [
    { ...original, version: 9 }, { ...original, essays: null }, { ...original, settings: [] },
    { ...original, categories: [...original.categories, original.categories[0]] },
    { ...original, topics: [{ ...original.topics[0], categoryId: 'missing' }] },
    { ...original, sentences: [{ ...original.sentences[0], categoryId: 'ending' }] },
    { ...original, sentences: [{ ...original.sentences[0], tags: [42] }] },
    { ...original, currentEssayId: 'missing' },
  ]
  for (const data of invalid) {
    await importFile(page, data)
    await expect(page.getByText('导入失败：', { exact: false })).toBeVisible()
    await expect(page.getByRole('button', { name: '确认覆盖导入' })).toHaveCount(0)
    expect(await stored(page)).toEqual(original)
  }
  await page.getByLabel('选择 JSON 备份文件').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{broken') })
  await expect(page.getByText('导入失败：', { exact: false })).toBeVisible()
  await importFile(page, original)
  await page.getByRole('button', { name: '取消导入' }).click()
  expect(await stored(page)).toEqual(original)
})

test('导入多篇作文并切换；导出排除 API Key；写入失败不覆盖内存', async ({ page }) => {
  await page.goto('/')
  const data = await stored(page)
  const second = { ...data.essays[0], id: 'second', title: '第二篇作文' }
  await navigate(page, '设置')
  await importFile(page, { ...data, essays: [...data.essays, second], currentEssayId: 'second', settings: { baseUrl: 'https://example.com', model: 'model', apiKey: 'secret' }, apiKey: 'root-secret' })
  await page.getByRole('button', { name: '确认覆盖导入' }).click()
  await navigate(page, '作文工作台')
  await expect(page.locator('#title')).toHaveValue('第二篇作文')
  await page.getByLabel('当前作文', { exact: true }).selectOption(data.essays[0].id)
  await expect(page.locator('#title')).toHaveValue('')
  await navigate(page, '设置')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出 JSON' }).click()
  const json = await readFile((await (await downloadPromise).path())!, 'utf8')
  expect(json).not.toContain('secret')
  expect(JSON.parse(json).essays).toHaveLength(2)
  const before = await stored(page)
  await importFile(page, data)
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError') } })
  await page.getByRole('button', { name: '确认覆盖导入' }).click()
  await expect(page.getByText('保存失败：本地存储不可用或空间不足，现有数据未更改。')).toBeVisible()
  expect(await stored(page)).toEqual(before)
  await navigate(page, '作文工作台')
  await expect(page.getByLabel('当前作文', { exact: true }).locator('option')).toHaveCount(2)
})

test('拒绝空白或重复名称，编辑句子期间切换收藏后保存不会回退', async ({ page }) => {
  await page.goto('/')
  await navigate(page, '素材库管理')
  await page.getByLabel('板块名称', { exact: true }).fill('   ')
  await page.getByRole('button', { name: '新增板块', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('名称不能为空。')
  await page.getByLabel('板块名称', { exact: true }).fill('情绪描写')
  await page.getByRole('button', { name: '新增板块', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('板块名称已存在。')
  await page.getByRole('button', { name: '编辑模板句', exact: true }).first().click()
  await page.getByRole('button', { name: '☆ 收藏', exact: true }).first().click()
  await page.getByLabel('英文', { exact: true }).fill('My heart was pounding.')
  await page.getByRole('button', { name: '保存模板句', exact: true }).click()
  await page.reload()
  await page.getByLabel('只看收藏').check()
  await expect(page.locator('.sentence')).toHaveCount(1)
  await expect(page.locator('.sentence')).toContainText('My heart was pounding.')
  await expect(page.getByRole('button', { name: '★ 已收藏' })).toBeVisible()
})
