import { test, expect } from '@playwright/test'

test('Submit 按顺序生成连续段落，段首句不标记，模板高亮且不改草稿', async ({ page }) => {
  await page.goto('/')
  await page.locator('#title').fill('A Little Courage')
  await page.locator('#source').fill('Original question, outside the continuation.')
  await page.locator('#paragraph1Starter').fill('My friend came over.')
  await page.locator('#paragraph2Starter').fill('At last, I smiled.')
  await page.getByRole('button', { name: '＋ 加入作文' }).first().click()
  const first = page.getByRole('region', { name: 'Paragraph 1', exact: true })
  await first.getByRole('button', { name: '＋ 添加连接文字' }).last().click()
  await first.getByTestId('text-block').getByRole('textbox').fill('  I took a deep breath.  ')
  await page.getByLabel('03 / 添加到哪一段').selectOption('paragraph2')
  await page.getByRole('button', { name: '＋ 加入作文' }).last().click()
  await page.getByRole('region', { name: 'Paragraph 2', exact: true }).getByTestId('template-block').getByRole('textbox').fill('We walked home together.')
  const before = await page.evaluate(() => localStorage.getItem('english-continuation:v1'))
  await page.getByRole('button', { name: 'Submit · 生成全文' }).click()
  const reader = page.getByRole('dialog', { name: '全文阅读' })
  await expect(reader).toBeVisible()
  const body = reader.getByRole('article', { name: '作文正文' })
  await expect(body.getByRole('heading')).toHaveText('A Little Courage')
  await expect(body.locator('.finished-paragraph')).toHaveCount(2)
  await expect(body.locator('.finished-paragraph').first()).toHaveText('My friend came over. My heart pounded as I stepped forward. I took a deep breath.')
  await expect(body.locator('.finished-paragraph').last()).toHaveText('At last, I smiled. We walked home together.')
  await expect(body.locator('mark')).toHaveCount(2)
  await expect(body.locator('mark').last()).toHaveText('We walked home together.')
  await expect(body).not.toContainText('Original question')
  await expect(body.locator('mark')).not.toContainText(['My friend came over.', 'At last, I smiled.'])
  expect(await page.evaluate(() => localStorage.getItem('english-continuation:v1'))).toBe(before)
  await page.screenshot({ path: 'test-results/finished-essay.png' })
  await page.keyboard.press('Escape')
  await expect(reader).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Submit · 生成全文' })).toBeFocused()
  await page.locator('#title').fill('An Updated Story')
  await page.getByRole('button', { name: 'Submit · 生成全文' }).click()
  await expect(reader.getByRole('heading', { name: 'An Updated Story' })).toBeVisible()
  await reader.getByRole('button', { name: '返回编辑' }).click()
  await expect(reader).toHaveCount(0)
})

test('空作文不可提交，普通文字与空块正确显示，窄屏正文不溢出', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Submit · 生成全文' })).toBeDisabled()
  const first = page.getByRole('region', { name: 'Paragraph 1', exact: true })
  await first.getByRole('button', { name: '＋ 添加连接文字' }).click()
  await first.getByTestId('text-block').getByRole('textbox').fill('Only my own words.')
  await first.getByRole('button', { name: '＋ 添加连接文字' }).last().click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Submit · 生成全文' }).click()
  const body = page.getByRole('article', { name: '作文正文' })
  await expect(body.locator('.finished-paragraph')).toHaveCount(1)
  await expect(body.locator('.finished-paragraph')).toHaveText('Only my own words.')
  await expect(body.locator('mark')).toHaveCount(0)
  expect(await page.getByRole('dialog').evaluate(e => e.scrollWidth <= e.clientWidth)).toBe(true)
})
