import { test, expect } from '@playwright/test'

test('完整组合流程：选句、排序、跨段、连接文字、编辑及刷新恢复', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('作文标题', { exact: true }).fill('A day to remember')
  await page.getByLabel('原文 / 题目', { exact: true }).fill('I was nervous before the school race.')
  await page.locator('#paragraph1Starter').fill('Then my friend came to me.')
  await page.locator('#paragraph2Starter').fill('Finally, I crossed the finish line.')
  const p1 = page.getByRole('region', { name: 'Paragraph 1', exact: true })
  const p2 = page.getByRole('region', { name: 'Paragraph 2', exact: true })
  await page.getByRole('button', { name: '＋ 加入作文' }).first().click()
  await page.getByLabel('01 / 选择板块').selectOption('action')
  await page.getByRole('button', { name: '＋ 加入作文' }).first().click()
  await p1.getByTestId('template-block').nth(1).getByRole('button', { name: '↑ 上移' }).click()
  await expect(p1.getByTestId('template-block').first().getByRole('textbox')).toHaveValue('Without hesitation, I rushed towards him.')
  await p1.getByRole('button', { name: '＋ 添加连接文字' }).nth(1).click()
  await p1.getByTestId('text-block').getByRole('textbox').fill('He smiled and encouraged me to keep going.')
  await expect(p1.locator('.essay-block').nth(1)).toHaveClass('essay-block text')
  await p1.getByTestId('template-block').last().getByRole('button', { name: '移至第 2 段' }).click()
  await p2.getByTestId('template-block').getByRole('textbox').fill('My heart pounded as I stepped onto the track.')
  await expect(p2.getByTestId('template-block')).toContainText('情绪描写 · 紧张')
  await page.getByLabel('03 / 添加到哪一段').selectOption('paragraph2')
  await page.getByLabel('01 / 选择板块').selectOption('ending')
  await page.getByRole('button', { name: '＋ 加入作文' }).first().click()
  await p2.getByTestId('template-block').first().getByRole('button', { name: '↓ 下移' }).click()
  await page.reload()
  await expect(page.getByLabel('作文标题', { exact: true })).toHaveValue('A day to remember')
  await expect(page.locator('#source')).toHaveValue('I was nervous before the school race.')
  await expect(page.locator('#paragraph1Starter')).toHaveValue('Then my friend came to me.')
  await expect(page.locator('#paragraph2Starter')).toHaveValue('Finally, I crossed the finish line.')
  await expect(p1.getByTestId('template-block').getByRole('textbox')).toHaveValue('Without hesitation, I rushed towards him.')
  await expect(p1.getByTestId('text-block').getByRole('textbox')).toHaveValue('He smiled and encouraged me to keep going.')
  await expect(p2.getByTestId('template-block').last().getByRole('textbox')).toHaveValue('My heart pounded as I stepped onto the track.')
  await expect(p2.getByTestId('template-block').last()).toContainText('情绪描写 · 紧张')
  await page.screenshot({ path: 'test-results/workbench.png', fullPage: true })
  await p2.getByTestId('template-block').last().getByRole('button', { name: '删除', exact: true }).click()
  await page.reload()
  await expect(p2.getByTestId('template-block')).toHaveCount(1)
})

test('全部板块可浏览，普通文字可跨段移动，边界排序禁用', async ({ page }) => {
  await page.goto('/')
  for (const category of ['emotion', 'action', 'thought', 'setting', 'interaction', 'plot', 'resolution', 'ending']) {
    await page.getByLabel('01 / 选择板块').selectOption(category)
    await expect(page.locator('.sentence')).toHaveCount(2)
    await page.locator('.topic').last().click()
    await expect(page.locator('.sentence')).toHaveCount(2)
  }
  const p1 = page.getByRole('region', { name: 'Paragraph 1', exact: true })
  const p2 = page.getByRole('region', { name: 'Paragraph 2', exact: true })
  await p1.getByRole('button', { name: '＋ 添加连接文字' }).click()
  await p1.getByTestId('text-block').getByRole('textbox').fill('I tried again.')
  await expect(p1.getByRole('button', { name: '↑ 上移' })).toBeDisabled()
  await expect(p1.getByRole('button', { name: '↓ 下移' })).toBeDisabled()
  await p1.getByRole('button', { name: '移至第 2 段' }).click()
  await expect(p2.getByTestId('text-block').getByRole('textbox')).toHaveValue('I tried again.')
  await expect(p2.getByTestId('template-block')).toHaveCount(0)
  await p2.getByRole('button', { name: '移至第 1 段' }).click()
  await expect(p1.getByTestId('text-block')).toHaveCount(1)
})

test('损坏草稿不会被默认空作文覆盖', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('english-continuation:v1', '{broken'))
  await page.reload()
  await expect(page.getByText('无法读取本地草稿', { exact: false })).toBeVisible()
  await page.locator('#title').fill('Do not overwrite')
  await expect.poll(() => page.evaluate(() => localStorage.getItem('english-continuation:v1'))).toBe('{broken')
})

test('存储写入失败时给出提示并允许继续编辑', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError') } })
  await page.goto('/')
  await page.locator('#title').fill('Still editable')
  await expect(page.locator('#title')).toHaveValue('Still editable')
  await expect(page.getByText('保存失败：', { exact: false })).toBeVisible()
})
